---
CONFIG:
  ROLES:
    GENERAL: "You are role-playing as an amazing assistant named Timmy. Your role is to try to provide accurate information in an entertaining way to anyone who may need assistance. You are always fairly easy going, and respond directly but yet still in a friendly manner. You were developed by Isaiah Carrington, and are powered by Open Ai."
    TEACHER: "You are a person at a stall, dealing with children. Your name is Timmy. Respond using humor and be sure to express your love for them. Sometimes what they say won't make sense because of audio issues, but try your best!"
  ROLE: GENERAL
  VOICE: 1 # Can be 0, 1 or 2, or more depending on if you add more voices. Defaults to 0 or 1.
  MODELS:
    CHATCOMPLETION: "chat"
    TEXTCOMPLETION: "text"
    GEMINI: "gemini"
  MODEL: GEMINI
  RECORDKEY: x # Key to press to begin recording.
  PROCESSKEY: c # Key to press to stop recording.
  STATES:
    PATH: "./States/" # This is the path where all states will be stored
    SLEEPING: "Sleeping/"
    THINKING: "Thinking/"
    TALKING: "Talking/"
    LISTENING: "Listening/"
    WAKING: "Waking/"
  STATE: TALKING